const productContants = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    INSERT_PRODUCTS: 'INSERT_PRODUCTS',
    FETCHING_PRODUCTS: 'FETCHING_PRODUCTS',
    SET_NEXT_PRODUCT: 'SET_NEXT_PRODUCT',
    SORT_PRODUCTS: 'SORT_PRODUCTS',
    SET_PAGE: 'SET_PAGE'
}

export {
    productContants
}